// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.15.8
// source: splitbillssummary.proto

package pd

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	SplitBillsSummary_List_FullMethodName = "/pd.SplitBillsSummary/List"
)

// SplitBillsSummaryClient is the client API for SplitBillsSummary service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SplitBillsSummaryClient interface {
	List(ctx context.Context, in *SplitBillsSummaryListReq, opts ...grpc.CallOption) (*SplitBillsSummaryListResp, error)
}

type splitBillsSummaryClient struct {
	cc grpc.ClientConnInterface
}

func NewSplitBillsSummaryClient(cc grpc.ClientConnInterface) SplitBillsSummaryClient {
	return &splitBillsSummaryClient{cc}
}

func (c *splitBillsSummaryClient) List(ctx context.Context, in *SplitBillsSummaryListReq, opts ...grpc.CallOption) (*SplitBillsSummaryListResp, error) {
	out := new(SplitBillsSummaryListResp)
	err := c.cc.Invoke(ctx, SplitBillsSummary_List_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SplitBillsSummaryServer is the server API for SplitBillsSummary service.
// All implementations must embed UnimplementedSplitBillsSummaryServer
// for forward compatibility
type SplitBillsSummaryServer interface {
	List(context.Context, *SplitBillsSummaryListReq) (*SplitBillsSummaryListResp, error)
	mustEmbedUnimplementedSplitBillsSummaryServer()
}

// UnimplementedSplitBillsSummaryServer must be embedded to have forward compatible implementations.
type UnimplementedSplitBillsSummaryServer struct {
}

func (UnimplementedSplitBillsSummaryServer) List(context.Context, *SplitBillsSummaryListReq) (*SplitBillsSummaryListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedSplitBillsSummaryServer) mustEmbedUnimplementedSplitBillsSummaryServer() {}

// UnsafeSplitBillsSummaryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SplitBillsSummaryServer will
// result in compilation errors.
type UnsafeSplitBillsSummaryServer interface {
	mustEmbedUnimplementedSplitBillsSummaryServer()
}

func RegisterSplitBillsSummaryServer(s grpc.ServiceRegistrar, srv SplitBillsSummaryServer) {
	s.RegisterService(&SplitBillsSummary_ServiceDesc, srv)
}

func _SplitBillsSummary_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SplitBillsSummaryListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SplitBillsSummaryServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SplitBillsSummary_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SplitBillsSummaryServer).List(ctx, req.(*SplitBillsSummaryListReq))
	}
	return interceptor(ctx, in, info, handler)
}

// SplitBillsSummary_ServiceDesc is the grpc.ServiceDesc for SplitBillsSummary service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SplitBillsSummary_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pd.SplitBillsSummary",
	HandlerType: (*SplitBillsSummaryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _SplitBillsSummary_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "splitbillssummary.proto",
}
