// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	splitBillsSummary "upi/app/business/com/api/internal/handler/splitBillsSummary"
	"upi/app/business/com/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/splitBillsSummary/list",
				Handler: splitBillsSummary.ListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/splitBillsSummary/export",
				Handler: splitBillsSummary.ExportHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/fundManage/v1"),
	)
}
