version: '3'

### 启动本项目之前，要先启动本项目的依赖环境

services:
  ### nginx 网关
  nginx-gateway:
    image: nginx:1.21.5
    container_name: nginx-gateway
    restart: always
    privileged: true
    environment:
      - TZ=Asia/Shanghai
    ports:
      - 82:8081
    volumes:
      - ./deploy/nginx/conf.d:/etc/nginx/conf.d
      - ./data/nginx/log:/var/log/nginx
    networks:
      - upi_net
    depends_on:
      - upi

  #前端api + 业务rpc
  upi:
    image: lyumikael/go-modd-env:v1.0.0
    container_name: upi
    environment:
      # 时区上海
      TZ: Asia/Shanghai
      GOPROXY: https://goproxy.cn,direct
    working_dir: /go/upi
    volumes:
      - .:/go/upi
    privileged: true
    restart: always
    networks:
      - upi_net

  etcd:
    image: bitnami/etcd:latest
    container_name: etcd
    restart: always
    networks:
      - upi_net
    ports:
      - "20000:2379"
      - "20001:2380"
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_NAME=etcd

  #zookeeper是kafka的依赖
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    environment:
      TZ: Asia/Shanghai
    restart: always
    ports:
      - 2181:2181
    networks:
      - upi_net

  #消息队列
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - 9092:9092
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=false
      - TZ=Asia/Shanghai
    restart: always
    #    volumes:
    #      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - upi_net
    depends_on:
      - zookeeper

  #asynqmon webui
  asynqmon:
    image: hibiken/asynqmon:latest
    container_name: asynqmon
    ports:
      - 8980:8080
    command:
      - '--redis-addr=upi-redis:6379'
      - '--redis-password=G62m50oigInC30sf'
    restart: always
    networks:
      - upi_net
    depends_on:
      - upi-redis

  #redis容器
  upi-redis:
    image: redis:6.2.5
    container_name: upi-redis
    ports:
      - 36379:6379
    environment:
      # 时区上海
      TZ: Asia/Shanghai
    volumes:
      # 数据文件
      - ./data/redis/data:/data:rw
    command: "redis-server --requirepass G62m50oigInC30sf  --appendonly yes"
    privileged: true
    restart: always
    networks:
      - upi_net

networks:
  upi_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.88.0.0/16
