// Code generated by goctl. DO NOT EDIT!
// Source: unionpay.proto

package unionpay

import (
	"context"

	"upi/app/unionpay/com/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	SavePayOrderReq  = pb.SavePayOrderReq
	SavePayOrderResp = pb.SavePayOrderResp

	Unionpay interface {
		SavePayOrder(ctx context.Context, in *SavePayOrderReq, opts ...grpc.CallOption) (*SavePayOrderResp, error)
	}

	defaultUnionpay struct {
		cli zrpc.Client
	}
)

func NewUnionpay(cli zrpc.Client) Unionpay {
	return &defaultUnionpay{
		cli: cli,
	}
}

func (m *defaultUnionpay) SavePayOrder(ctx context.Context, in *SavePayOrderReq, opts ...grpc.CallOption) (*SavePayOrderResp, error) {
	client := pb.NewUnionpayClient(m.cli.Conn())
	return client.SavePayOrder(ctx, in, opts...)
}
