// Code generated by goctl. DO NOT EDIT!
// Source: customer.proto

package server

import (
	"context"

	"upi/app/unionpay/com/rpc/internal/logic"
	"upi/app/unionpay/com/rpc/internal/svc"
	"upi/app/unionpay/com/rpc/pb"
)

type StreamGreeterServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedStreamGreeterServer
}

func NewStreamGreeterServer(svcCtx *svc.ServiceContext) *StreamGreeterServer {
	return &StreamGreeterServer{
		svcCtx: svcCtx,
	}
}

func (s *StreamGreeterServer) Greet(ctx context.Context, in *pb.StreamReq) (*pb.StreamResp, error) {
	l := logic.NewGreetLogic(ctx, s.svcCtx)
	return l.Greet(in)
}
