// Code generated by goctl. DO NOT EDIT!
// Source: unionpay.proto

package server

import (
	"context"

	"upi/app/unionpay/com/rpc/internal/logic"
	"upi/app/unionpay/com/rpc/internal/svc"
	"upi/app/unionpay/com/rpc/pb"
)

type UnionpayServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedUnionpayServer
}

func NewUnionpayServer(svcCtx *svc.ServiceContext) *UnionpayServer {
	return &UnionpayServer{
		svcCtx: svcCtx,
	}
}

func (s *UnionpayServer) SavePayOrder(ctx context.Context, in *pb.SavePayOrderReq) (*pb.SavePayOrderResp, error) {
	l := logic.NewSavePayOrderLogic(ctx, s.svcCtx)
	return l.SavePayOrder(in)
}
