// Code generated by goctl. DO NOT EDIT!
// Source: splitbillssummary.proto

package splitbillssummary

import (
	"context"

	"upi/app/business/com/rpc/pd"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	SplitBillsSummaryListMap  = pd.SplitBillsSummaryListMap
	SplitBillsSummaryListReq  = pd.SplitBillsSummaryListReq
	SplitBillsSummaryListResp = pd.SplitBillsSummaryListResp
	StreamReq                 = pd.StreamReq

	SplitBillsSummary interface {
		List(ctx context.Context, in *SplitBillsSummaryListReq, opts ...grpc.CallOption) (*SplitBillsSummaryListResp, error)
	}

	defaultSplitBillsSummary struct {
		cli zrpc.Client
	}
)

func NewSplitBillsSummary(cli zrpc.Client) SplitBillsSummary {
	return &defaultSplitBillsSummary{
		cli: cli,
	}
}

func (m *defaultSplitBillsSummary) List(ctx context.Context, in *SplitBillsSummaryListReq, opts ...grpc.CallOption) (*SplitBillsSummaryListResp, error) {
	client := pd.NewSplitBillsSummaryClient(m.cli.Conn())
	return client.List(ctx, in, opts...)
}
