// Code generated by goctl. DO NOT EDIT!
// Source: account.proto

package account

import (
	"context"

	"upi/app/account/com/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AccountData             = pb.AccountData
	AccountListReq          = pb.AccountListReq
	AccountListResp         = pb.AccountListResp
	GetSubAcctNoPassUidReq  = pb.GetSubAcctNoPassUidReq
	GetSubAcctNoPassUidResp = pb.GetSubAcctNoPassUidResp

	Account interface {
		AccountList(ctx context.Context, in *AccountListReq, opts ...grpc.CallOption) (*AccountListResp, error)
		GetSubAcctNoPassUid(ctx context.Context, in *GetSubAcctNoPassUidReq, opts ...grpc.CallOption) (*GetSubAcctNoPassUidResp, error)
	}

	defaultAccount struct {
		cli zrpc.Client
	}
)

func NewAccount(cli zrpc.Client) Account {
	return &defaultAccount{
		cli: cli,
	}
}

func (m *defaultAccount) AccountList(ctx context.Context, in *AccountListReq, opts ...grpc.CallOption) (*AccountListResp, error) {
	client := pb.NewAccountClient(m.cli.Conn())
	return client.AccountList(ctx, in, opts...)
}

func (m *defaultAccount) GetSubAcctNoPassUid(ctx context.Context, in *GetSubAcctNoPassUidReq, opts ...grpc.CallOption) (*GetSubAcctNoPassUidResp, error) {
	client := pb.NewAccountClient(m.cli.Conn())
	return client.GetSubAcctNoPassUid(ctx, in, opts...)
}
