// Code generated by goctl. DO NOT EDIT!
// Source: account.proto

package server

import (
	"context"

	"upi/app/account/com/rpc/internal/logic"
	"upi/app/account/com/rpc/internal/svc"
	"upi/app/account/com/rpc/pb"
)

type AccountServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedAccountServer
}

func NewAccountServer(svcCtx *svc.ServiceContext) *AccountServer {
	return &AccountServer{
		svcCtx: svcCtx,
	}
}

func (s *AccountServer) AccountList(ctx context.Context, in *pb.AccountListReq) (*pb.AccountListResp, error) {
	l := logic.NewAccountListLogic(ctx, s.svcCtx)
	return l.AccountList(in)
}
